import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import GlobalStylesProviders from "./providers/GlobalStylesProviders";
import ContextProvider from "./providers/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>      
          <GlobalStylesProviders>
            <Sidebar />
            {children}    
          </GlobalStylesProviders>     
        </ContextProvider>  
        </body>
    </html>
  );
}
